FIXUP: CHROMIUM: virtio: Update virtgpu buffer sharing API
0-day reports:

virtio_video_device.c:(.text+0xc00): undefined reference to `virtio_dma_buf_get_uuid'

VIRTIO_VIDEO now unconditionally requires VIRTIO_DMA_SHARED_BUFFER.
Since VIRTIO_DMA_SHARED_BUFFER depends on VIRTIO_MENU, which is
independent of VIRTIO, VIRTIO_VIDEO now unconditionally depends on
VIRTIO_MENU as well.

This still leaves

WARNING: unmet direct dependencies detected for VIRTIO_DMA_SHARED_BUFFER
  Depends on [n]: VIRTIO_MENU [=n] && DMA_SHARED_BUFFER [=y]
  Selected by [m]:
  - DRM_VIRTIO_GPU [=m] && HAS_IOMEM [=y] && DRM [=m] && VIRTIO [=y] && MMU [=y] && PCI [=y]

which is seen if VIRTIO_MENU is disabled. This problem was introduced by
commit 7c5e01902547 ("BACKPORT: FROMGIT: virtio: fix build for configs
without dma-bufs"). Since that commit, DRM_VIRTIO_GPU depends on
VIRTIO_MENU as well. Add that dependency.

BUG=b:142423916
TEST=Test builds

Change-Id: Ifa87ff51b39bf39feffc28e65c3c346a324415c9
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2410825
Reviewed-by: David Stevens <stevensd@chromium.org>
[5.4-arcvm: picked from 5.4 for initial merge]

[alexander.gordeev@opensynergy.com:
* Cherry picked from https://github.com/Gnurou/linux/commit/f71d2bdc5cda.]

Issue: COQOS-17349